/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Powers the 'Create Alert' preset picker — one entry per demo scenario, sourced
         *     directly from the fixtures so the UI can never drift from what's actually mocked.
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Alert
         * @description Single ingress path for both the webhook and the 'Create Alert' UI button —
         *     both post this exact shape. A preset click can send just `{"scenario": "..."}`;
         *     a raw webhook must send title/service/severity/message directly.
         */
        post: operations["create_alert_api_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_api_investigations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Investigation */
        get: operations["stream_investigation_api_investigations__investigation_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_investigations__investigation_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Follow Up Route */
        post: operations["ask_follow_up_route_api_investigations__investigation_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionKind
         * @enum {string}
         */
        ActionKind: "immediate_mitigation" | "verification" | "durable_fix";
        /** AgentStep */
        AgentStep: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Tool Name */
            tool_name: string | null;
            /** Tool Input */
            tool_input: {
                [key: string]: unknown;
            } | null;
            /** Tool Output Summary */
            tool_output_summary: string | null;
            status: components["schemas"]["AgentStepStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Error */
            error: string | null;
        };
        /**
         * AgentStepStatus
         * @enum {string}
         */
        AgentStepStatus: "running" | "complete" | "error";
        /** Alert */
        Alert: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Service */
            service: string;
            severity: components["schemas"]["Severity"];
            /** Message */
            message: string;
            /** Stack Trace */
            stack_trace: string | null;
            /**
             * Fired At
             * Format: date-time
             */
            fired_at: string;
            /** @default manual */
            source: components["schemas"]["AlertSource"];
            /** Scenario */
            scenario: string | null;
        };
        /**
         * AlertSource
         * @enum {string}
         */
        AlertSource: "webhook" | "manual";
        /** AskFollowUpRequest */
        AskFollowUpRequest: {
            /** Question */
            question: string;
        };
        /** AskFollowUpResponse */
        AskFollowUpResponse: {
            /** Answer */
            answer: string;
            /** Cited Evidence Ids */
            cited_evidence_ids: string[];
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /**
         * CreateAlertRequest
         * @description Body for POST /api/alerts. A raw-JSON alert (from a real webhook) supplies title/
         *     service/severity/message directly. A scenario-preset alert (from the 'Create Alert'
         *     UI) may supply only `scenario` — the server fills the rest in from the fixture's
         *     AlertTemplate, so the frontend never duplicates alert content that already lives in
         *     the fixtures. Any field given explicitly overrides the scenario's default.
         */
        CreateAlertRequest: {
            /** Title */
            title?: string | null;
            /** Service */
            service?: string | null;
            severity?: components["schemas"]["Severity"] | null;
            /** Message */
            message?: string | null;
            /** Stack Trace */
            stack_trace?: string | null;
            /** Fired At */
            fired_at?: string | null;
            /** @default manual */
            source: components["schemas"]["AlertSource"];
            /** Scenario */
            scenario?: string | null;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            kind: components["schemas"]["EvidenceKind"];
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Occurred At */
            occurred_at: string | null;
            /** Source Url */
            source_url: string | null;
        };
        /**
         * EvidenceKind
         * @enum {string}
         */
        EvidenceKind: "commit" | "pull_request" | "deploy" | "code_owner" | "log" | "metric" | "error_group" | "service_map";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hypothesis */
        Hypothesis: {
            /** Id */
            id: string;
            /** Rank */
            rank: number;
            /** Summary */
            summary: string;
            /** Reasoning */
            reasoning: string;
            confidence: components["schemas"]["Confidence"];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Suggested Actions */
            suggested_actions: components["schemas"]["SuggestedAction"][];
        };
        /** Investigation */
        Investigation: {
            /** Id */
            id: string;
            alert: components["schemas"]["Alert"];
            /** @default queued */
            status: components["schemas"]["InvestigationStatus"];
            /** Tldr */
            tldr: string | null;
            /** Steps */
            steps: components["schemas"]["AgentStep"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Hypotheses */
            hypotheses: components["schemas"]["Hypothesis"][];
            /** Feedback */
            feedback: components["schemas"]["InvestigationFeedback"][];
            /** Warnings */
            warnings: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Total Tool Calls
             * @default 0
             */
            total_tool_calls: number;
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /** Wall Time Ms */
            wall_time_ms: number | null;
            /** Error */
            error: string | null;
        };
        /** InvestigationFeedback */
        InvestigationFeedback: {
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Helpful */
            helpful: boolean;
            /** Actual Root Cause */
            actual_root_cause?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * InvestigationStatus
         * @enum {string}
         */
        InvestigationStatus: "queued" | "triaging" | "investigating" | "synthesizing" | "complete" | "needs_input" | "failed";
        /** ScenarioSummary */
        ScenarioSummary: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Service */
            service: string;
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
        /**
         * SubmitFeedbackRequest
         * @description Body for POST /investigations/{id}/feedback. `created_at` is server-set on
         *     the resulting InvestigationFeedback — the client's clock isn't trustworthy and
         *     doesn't need to be.
         */
        SubmitFeedbackRequest: {
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Helpful */
            helpful: boolean;
            /** Actual Root Cause */
            actual_root_cause?: string | null;
        };
        /** SuggestedAction */
        SuggestedAction: {
            /** Id */
            id: string;
            kind: components["schemas"]["ActionKind"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Command */
            command: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    create_alert_api_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_api_investigations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"][];
                };
            };
        };
    };
    get_investigation_api_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_investigation_api_investigations__investigation_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_investigations__investigation_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_follow_up_route_api_investigations__investigation_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskFollowUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskFollowUpResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
